config/routes.rb
RsvpLabApp::Application.routes.draw do
  resources :invites

  resources :events

  resources :users

  root 'users#index'

  get 'events/:id/invites/new' => 'invites#new'
  get 'users/:id/events/new' => 'events#new'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :invites
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :event

  def invited_user
    Invite.find_by(name: self.name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :invites, :through => :events
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def new
    @event = Event.new
    @user = User.find(params[:id])
  end

  def create
    if Event.create(event_params)
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(param[:id])

    if @event.update_attributes(event_params)
      redirect_to action: 'index'
    else
      render action: 'edit', id: @event
    end
  end

  def destroy
    event = Event.find(params[:id]).destroy
    redirect_to action: 'index'
  end

  private

  def event_params
    params.require(:event).permit(:name, :user_id)
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def index
    @invites = Invite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invites }
    end
  end

  def new
    @invite = Invite.new
    @event = Event.find(params[:id])
  end

  def create
    if Invite.create(invite_params)
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def show
    @invite = Invite.find(params[:id])
  end

  def edit
    @invite = Invite.find(params[:id])
  end

  def update
    @invite = Invite.find(param[:id])

    if @invite.update_attributes(invite_params)
      redirect_to action: 'index'
    else
      render action: 'edit', id: @invite
    end
  end

  def destroy
    invite = Invite.find(params[:id]).destroy
    redirect_to action: 'index'
  end

  private

  def invite_params
    params.require(:invite).permit(:name, :message, :event_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    if User.create(user_params)
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(param[:id])

    if @user.update_attributes(user_params)
      redirect_to action: 'index'
    else
      render action: 'edit', id: @user
    end
  end

  def destroy
    user = User.find(params[:id]).destroy
    redirect_to action: 'index'
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>

<%= form_for @event, url: {action: "update"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= collection_select(:event, :user_id, User.all, :id, :name, prompt: true) %>
  
  <%= f.submit "Update" %>
<% end %>

<a href="/events">Cancel</a>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
  <%= link_to event.name, event_path(event) %>,
    created by <%= event.user.name %><br>
    <%= link_to "Invite peepz", "/events/#{event.id}/invites/new" %><br><br>
<% end %><br>

<p>To create a new event, please select a <%= link_to "user page", controller: "users", action: "index" %>
.</p>

app/views/events/new.html.erb
<h1>Hi <%= @user.name %>! Create a new event.</h1>

<%= form_for @event, url: {action: "create"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.hidden_field :user_id, value: @user.id %>

  <%= f.submit "Create" %>
<% end %>

<a href="/events">Cancel</a>

app/views/events/show.html.erb
<h1>Event: <%= @event.name %></h1>

<% unless @event.invites.empty? %>
  <p>Invited:</p>
  <ol>
    <% @event.invites.each do |invite| %>
      <li><%= link_to invite.event.user.name, invite.event.user %> | 
        RSVP: <%= invite.event.user.rsvp ? "Yes" : "No" %></li>
    <% end %>
  </ol><br>
<% end %>

<p><strong><a href="/events/<%= @event.id %>/invites/new">Create new invite</a></strong></p>

<a href="/events">Back</a> | 
<a href="/events/<%= @event.id %>/edit">Edit</a> | 
<%= button_to 'Destroy', @event, :method => :delete %>

app/views/invites/edit.html.erb
<h1>Edit <%= @invite.name %></h1>

<%= form_for @invite, url: {action: "update"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :message %>:
  <%= f.text_field :message %><br />

  <%= collection_select(:invite, :event_id, Event.all, :id, :name, prompt: true) %>
  
  <%= f.submit "Update" %>
<% end %>

<a href="/invites">Cancel</a>

app/views/invites/index.html.erb
<h1>Invites</h1>
<ul>
  <% @invites.each do |invite| %>
    <li>Invitation for <%= link_to invite.name, invite.invited_user %> to come to <%= link_to invite.event.name, invite.event %> <br> Message: <%= invite.message %> </li><br>
  <% end %>
</ul>

To create more invites, first choose an <%= link_to "event", controller: "events", action: "index" %>

app/views/invites/new.html.erb
<h1>Create a new invite</h1>

<%= form_for @invite, url: {action: "create"} do |f| %>

  Who would you like to invite?<br>
  <%= collection_select(:invite, :name, User.all, :name, :name, prompt: true) %>

  <%= f.label :message %>:
  <%= f.text_field :message %><br />

  <%= f.hidden_field :event_id, value: @event.id %>

  <%= f.submit "Create" %>
<% end %>

<a href="/invites">Cancel</a>

app/views/invites/show.html.erb
<h1>Invitation for <%= @invite.user.name %> to <%= @invite.event.name %></h1>

<h2>Message</h2>
<%= @invite.message %>

<a href="/invites">Back</a> | 
<a href="/invites/<%= @invite.id %>/edit">Edit</a> | 
<%= button_to 'Destroy', @invite, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RsvpLabApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= form_for @user, url: {action: "update"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
    
  <%= f.submit "Update" %>
<% end %>

<a href="/users">Cancel</a>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %> | <%= link_to "Invites", "#" %><br>
<% end %><br>
<br>

<%= link_to "Create a new user", action: "new" %>

app/views/users/new.html.erb
<h1>Create a new user</h1>

<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.submit "Create" %>
<% end %>

<a href="/users">Cancel</a>

app/views/users/show.html.erb
<h1>User: <%= @user.name %></h1>

<% unless @user.events.empty? %>
  <p>Events:</p>
  <ol>
    <% @user.events.each do |event| %>
      <li><a href="/events/<%= event.id %>"><%= event.name %></a></li>
    <% end %>
  </ol><br>
<% end %><br>

<%= link_to "Create a new event as #{@user.name}", "/users/<%= @user.id %>/events/new" %>

<a href="/users">Back</a> | 
<a href="/users/<%= @user.id %>/edit">Edit</a> | 
<%= button_to 'Destroy', @user, :method => :delete %>